### ISSUE TITLE
Syntax error:  "(" unexpected

### ISSUE THREAD

**Issue by amonetlol** [c-thun/10ify#2] opened 2020-05-15 03:45 UTC
Installing Dependencies...
Setting Up Basic Files...
Installing Animation Tweaks...
Installing Dash to Panel...
Installing Arc Menu...
Modifying the look and feel
install.sh: 102: Syntax error: "(" unexpected

**Comment by ghost** [comment] 2020-05-15 23:18
Try running the script again. If the problem persists, reply back here. I'm not sure why this is happening. Will spin a VM and check it

**Comment by ghost** [comment] 2020-05-23 10:15
Have checked the code. Unable to reproduce. Manually run the script multiple times without this issue occurring ever again. Closing the issue

**Closed as completed by ghost** 2020-05-23 10:15 UTC
